### PR TITLE
Made less nesting

### PR DESCRIPTION
**Pull request by BlackSoulHub**
This is my first such contribution. If I did something wrong, please write about it

### CODE REVIEW

**Review by starovoid — CHANGES_REQUESTED** [review]
Nesting reduction looks good, but it would be better to combine `None` processing in command together with getting values. This will improve the readability of the code in the future and will not confuse unnecessary `.unwrap()`.

I suggest using the following code 
```rust
let (operation, args) = match command {
    Some(cmd) => cmd,
    None => {
        println!("Command is not set");
        return;
    }
};
```

instead of
```rust
if command.is_none() {
    println!("Command is not set");
    return;
}

let (operation, args) = command.unwrap();
```

Before I can approve merge, I will wait for these changes.

**Comment by BlackSoulHub** [comment]
> ```rust
> let (operation, args) = match command {
>     Some(cmd) => cmd,
>     None => {
>         println!("Command is not set");
>         return;
>     }
> };
> ```
Looks beautiful. I'll fix it now.

**Comment by BlackSoulHub** [comment]
I was thinking about creating a similar function:
```rust
fn process_command(operation: &str, args: &ArgMatches) -> Result<(), CustomError> {
    let handler = match HANDLERS.get(operation) {
        Some(handler) => handler,
        None => {
            return Err(CustomError::UnknownCommand)
        }
    };

    handler()
}
```

**Review by starovoid — APPROVED** [review]
All right. By the way, I recommend running "cargo fmt" before committing to format the code in accordance with general standards.

**Pull request merged**
